# Generated by Django 4.1.7 on 2023-05-25 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_rename_occutpion_patient_occupation_and_more'),
        ('doctors', '0009_remove_doctor_institution_alter_doctor_study'),
        ('consult', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.doctor'),
        ),
        migrations.AlterField(
            model_name='consult',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.patient'),
        ),
    ]
