# Generated by Django 4.1.7 on 2023-04-12 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback',
            field=models.TextField(null=True),
        ),
    ]
