# Generated by Django 4.1.7 on 2023-04-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_feedback_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True),
        ),
    ]
