# Generated by Django 4.1.7 on 2023-05-25 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_doctor_gender'),
        ('patient', '0004_patient_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='occutpion',
            new_name='occupation',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='phone_numer',
            new_name='phone_number',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.doctor'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.patient'),
        ),
    ]
