# Generated by Django 4.1.7 on 2023-04-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_doctor_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='gender',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='total_consult',
            field=models.IntegerField(default=0),
        ),
    ]
