# Generated by Django 4.1.7 on 2023-05-30 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0019_alter_profil_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profil',
        ),
    ]
